### ISSUE TITLE
小建议-HTTP记录原始请求

### ISSUE THREAD

**Issue by XTeam-Wing** [Buzz2d0/Hyuga#11]
http 和dns record可以直接记录原始的请求。对测试帮助比较大
demo参考 https://app.interactsh.com/

**Comment by Buzz2d0** [comment]
http 记录原始请求：https://github.com/Buzz2d0/Hyuga/blob/master/hyuga/handler/oob/http.go#L21
dns 记录了 query name ：https://github.com/Buzz2d0/Hyuga/blob/master/hyuga/handler/oob/dns.go#L59

如果把服务搭建起来，这样的话效果会更直观一些

**Comment by Buzz2d0** [comment]
> http 记录原始请求：https://github.com/Buzz2d0/Hyuga/blob/master/hyuga/handler/oob/http.go#L21 dns 记录了 query name ：https://github.com/Buzz2d0/Hyuga/blob/master/hyuga/handler/oob/dns.go#L59
> 
> 得去把服务搭建起来，这样的话效果会更直观一些 :(

TODO: 安排上了，等下班了去找台主机✌🏼

**Comment by XTeam-Wing** [comment]
👍
