### ISSUE TITLE
部署后访问显示空白页

### ISSUE THREAD

**Issue by StefanoWen** [Buzz2d0/Hyuga#14]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/32628282/154913818-558579dd-3b50-4256-b6c1-601563f4650c.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/32628282/154913852-ee161b39-bbcc-4937-ada5-23abe1a9624f.png">
按照部署步骤，`docker-compose && docker-compose up`之后访问web页面就是空白的，没有前段资源返回，是什么问题呢？

**Comment by Buzz2d0** [comment]
直接访问 `127.0.0.1` 就是这样的，代码逻辑如下：
<img width="525" alt="image" src="https://user-images.githubusercontent.com/26270009/156890106-d11581b6-5ca7-47eb-8d70-5a6e339ac16b.png">

正确的方式是去访问 config.yaml 文件设置的主域名：[main](https://github.com/Buzz2d0/Hyuga/blob/master/hyuga/config.yaml#L5)

在本地测试的话，修改 `/etc/hosts` 文件：
```
127.0.0.1       hyuga.io
```

之后直接访问：http://hyuga.io

**Comment by Buzz2d0** [comment]
用 docker-compose 重新跑一遍，无法复现你的问题，完成正常：

`$ cat /etc/hosts`:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/26270009/157160739-7c1d5261-5190-49f8-8d14-0f9de5b5a823.png">


`$ docker-compose build && docker-compose up`:

![](https://user-images.githubusercontent.com/26270009/157160557-6c627142-f507-4397-bc6c-25e6f646b259.png)

浏览器无痕模式打开

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/26270009/157161066-d0e9682f-029f-494c-aef0-e5179bfc22de.png">

**Comment by StefanoWen** [comment]
重新编译以后可以了，3q
