### ISSUE TITLE
师傅的API在哪里哇？？？

### ISSUE THREAD

**Issue by zhzyker** [Buzz2d0/Hyuga#5]
我翻了翻源码看看似乎是 http://api.hyuga.co/?token=zH61HdGgEm7ETLoFpNhjZJePoR99dy0op9PKBP5&type=dns

但是又没有记录，特此求助API在哪里哇？

**Comment by zhzyker** [comment]
emm我去抓包瞧了瞧找到了~
http://api.hyuga.co/v1/records?type=dns&token=JF5nwRj1FXPsZgFRZZ1fpyChBL2Iay2GJ27c410yYs78PU3TSpc95  

建议师傅完善一哈readme里关于api的说明哇，给师傅的平台打call

**Comment by Buzz2d0** [comment]
已经添加啦~
https://github.com/Buzz2d0/Hyuga#%E6%9F%A5%E8%AF%A2-api
