### ISSUE TITLE
docker-compose build 爆错

### ISSUE THREAD

**Issue by FishM4n** [Buzz2d0/Hyuga#7]
[root@hhh Hyuga-master]# docker-compose build
redis uses an image, skipping
Building ui
Step 1/10 : FROM node:lts-alpine as builder
ERROR: Service 'ui' failed to build: Error parsing reference: "node:lts-alpine as builder" is not a valid repository/tag: invalid reference format

**Comment by Buzz2d0** [comment]
Refer to this https://stackoverflow.com/questions/48848020/dockerfile-is-not-a-valid-repository-tag-invalid-reference-format/50812972 

check docker versions
```shell
docker -v
docker-compose -v
```

**Comment by FishM4n** [comment]
解决，感谢
