### ISSUE TITLE
没有登录认证吗

### ISSUE THREAD

**Issue by handbye** [Buzz2d0/Hyuga#8]

**Comment by Buzz2d0** [comment]
更想做一个像 dnslog.cn 的开放平台

**Comment by handbye** [comment]
> 更想做一个像 dnslog.cn 的开放平台

个人感觉使用这个项目的大部分是私有化部署，私有化部署后供团队使用需暴露在公网，要是没认证的话有点不方便。不过还是感谢作者提供的平台。
